package com.example.moneycache;

import java.util.ArrayList;
import java.util.List;

/**
 * builds the BankData object with only the data stored in DB.
 * Data variables are listed in the same order as in the json file.
 * **Reads the bankData.txt file***
 * TODO: bring this data in from the DB
 */
public class BankData {
    //TODO: Ask Bro. Macbeth about this list that was generated by ItemFragment.java line 67
    public static final List<BankData> ITEMS = new ArrayList<>();
    private String date;
    // description would be the string that describes the payee or payer, my bank uses 'memo'
    private String description;
    // amount can be positive for income or negative for expense
    //TODO: cast string from json into float---are the constructors enough??
    private Float amount;
    // amount2 for files that have separate debit and credit columns
    //private float amount2;


    public BankData(String date, String description, String amount) {
        this.date = date;
        this.description = description;
        this.amount = Float.parseFloat(amount);
    }
    public BankData(String date, String description, String amount, String amount2) {
        this.date = date;
        this.description = description;
        this.amount = Float.parseFloat(amount) + Float.parseFloat(amount2);
        //this.amount2 = amount2;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }
    public String getStringAmount() {
        return Float.toString(amount);
    }


}


